source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'rgbycch_swift_api_Tests', :exclusive => true do
  pod "rgbycch_swift_api", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
